#
# Copyright (C) 2021 Kian Cross
#

name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "30 23 * * 3"

jobs:
  build:
    name: Build (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [11, 15, 16]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build 🧰
        run: ./gradlew jar

      - name: Cleanup Gradle Cache
        shell: bash
        run: |
          ./gradlew --stop
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
  
  test:
    name: Test (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    strategy:
      matrix:
        java: [11, 15, 16]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test 🔬
        run: ./gradlew test
      
      - name: Upload Coverage Report 📤
        uses: codecov/codecov-action@v1
        env:
          JAVA_VERSION: ${{ matrix.java }}
        with:
          fail_ci_if_error: true
          env_vars: OS,JAVA_VERSION

      - name: Cleanup Gradle Cache
        shell: bash
        run: |
          ./gradlew --stop
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
  
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v2

      - name: Initialize CodeQL ⚙️
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - name: Build 🧰
        run: ./gradlew jar

      - name: Perform CodeQL Analysis 🤖
        uses: github/codeql-action/analyze@v1
